# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d747e29c74ece897228a497e9c22955caad5ad6b01c1a5e29bcc027b23273915378b18c56a49834e547027d99a896c335fdb1600ffb73fdb1034352db58ec3c1

test:
  secret_key_base: a8f95fe00e54a44af1f83c3a0c3fe5fa0a64ef52f96d3a4b1196bb6cabbbd560f68ee1cd382f610817e2347caa45d071d52b8358be5992bb0d4adfefd8fd50af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
